### PR TITLE
Injected Reducers Example

### PR DESCRIPTION
**Pull request by jnishiyama**
I not sure this is a particularly good example, but it took me a good amount of time to understand how to implement the state manager given the way I was injecting async reducers, so I figured I'd add this here if relevant.

### CODE REVIEW

**Comment by rt2zz** [comment]
When is injecting reducers useful? code looks good, but I want to understand the cases when this is useful.

**Comment by jnishiyama** [comment]
I use it to make code splitting possible. Since the application doesn't have all my js files at initial load, I need to inject the reducers when the js files are loaded.

**Comment by heygrady** [comment]
This pattern is very common when working with [`react-redux-starter-kit`](https://github.com/davezuko/react-redux-starter-kit). That project has 8,700 stars as of this writing. It's very popular and recommends "injecting" reducers for code splitting purposes. This has been causing issues with redux libraries that aren't expecting the reducers to be replaced on most route changes.

There's a good thread here: https://github.com/davezuko/react-redux-starter-kit/issues/1055

My two cents on that thread: https://github.com/davezuko/react-redux-starter-kit/issues/1055#issuecomment-287220460

I'm here right now because I'm trying to debug an issue where dev tools and redux-persist are duking it out over my injected reducers. I'm hoping this solution helps me.

**Update:** This didn't help. I've disabled `redux-devtools-extention` on my project.

**Comment by rt2zz** [comment]
ty

**Pull request merged**
